# Generated by Django 4.2.5 on 2023-10-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231027_0948'),
        ('book', '0003_auto_20231027_0934'),
    ]

    operations = [
    ]
