# Generated by Django 4.2.5 on 2023-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231213_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_by',
            field=models.TextField(null=True),
        ),
    ]
