# Generated by Django 4.2.5 on 2023-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_productreview_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='judul_buku',
            field=models.TextField(null=True),
        ),
    ]
