# Generated by Django 4.2.4 on 2023-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_updates_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='author_username',
            field=models.CharField(default='author', max_length=150),
        ),
    ]
