# Generated by Django 4.2.6 on 2023-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reader',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('READER', 'Reader')], default='READER', max_length=10),
        ),
    ]
